travis:
  secure:
    BINSTAR_TOKEN: 20HIpQktw6TgZfeQae6WR5ctnnXYyFkmzE0rD86yOm2wAWgghXJuK5A0WA4OKfCRZfj3Dcug42EuvvtG1fG2Wapz+L2PWmDtvHH2RVfWA9k2qa5boUufTq+b7/5VDG9rc1tJLggxkAAWKuZkqffMnyT6Afa1GLl6Ppm8/ct+VlEeqQfxVSnNk7fNRuFHB1prYQVySPtrZnWvMCtrUPT5rtdoix3Exo3njk3OXf0nBhhM4hnSAremhdbBVLQMVZ4VdyNinEYqbPa2ijVeAA8ZEefFUcMDrYmRN6Vq77UsLHioumTV0cuyWshmFC9WsLAckrIKLneKYx5RPfDpUM/BYbaS7nROL0VujEd0tLqMo3tGcjS5ikJBpJi8CPCpE/nuvUZFoL1OYUduucbECr9ZrFUz3oLG8hIqUcACbuGTXZ2Q8fOVZnVEUC2wK4gAf7qtCyXtyIKC9905H/5qWMoqZtUZ76ks/6HO2dKKDZhCL1vumVKTV6pkyfKQZzmcZh8gfbvDPqcKfZm3qrZxAM2NuX2sRb/Ya8rgzrhiHHXFImhD/HaqEu6wqxSFfY14adgTcEEK5+NAQlmA3K+WNm8q0DLaU9ByMFPUlYK9jsQFZZmxfqyO+UVnNf0XVq8nxSsJTqMPkcvpkzgivcyttW+XXVc3JdacjlELte4YQVJWbsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
